on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: npm install

      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          sparse-checkout: reports

      - name: Run scanner
        run: xvfb-run npm start

      - name: Deploy results
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./reports
          github_token: ${{ secrets.GITHUB_TOKEN }}
